name: Node.js CI

on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: self-hosted
  
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: |
        sudo /usr/bin/git pull /redx/frontend/
        sudo docker stop redx-front-react-production
        sudo docker rm redx-front-react-production
        sudo docker build -t group09/frontend-react-production /redx/frontend/frontend-react
        sudo docker run --env-file /redx/frontend/frontend-react/prod.env -d -p 3000:3000 --name redx-front-react-production group09/frontend-react-production

